### ISSUE TITLE
Alternatives to markdown?

### ISSUE THREAD

**Issue by KantarBruceAdams** [mpark/wg21#2]
I came across [how-i-format-my-cpp-papers](https://mpark.github.io/programming/2018/11/16/how-i-format-my-cpp-papers/) and wanted to ask if you were aware of [asciidoc](https://asciidoctor.org/) and other alternatives to markdown?

There is no option to comment on your blog. I thought it better to ask here rather than email you directly as it could otherwise be asked a few times. 

This is not a criticism or defect report and you are of course free to use whatever you want.
You might interpret this as a feature request for a companion blog entry "why Markdown is for me?" which you are free to reject.

asciidoc, if you don't know of it, is similar to markdown but much less limiting. You can write entire books in it (it can be mapped to docbook). 
I've found it a very good fit for small specifications and where I want to generate both html and PDF.

There are other alternatives as well and its quite a deep well to explore but I think its interesting when someone settles on one to understand their reasons. I've observed people often start with pure Markdown and discover the alternatives only when they get fed up with its limitations.
Coming from LaTeX the limitations must have been more visible to you at the outset which should make for an interesting perspective.

**Comment by mpark** [comment]
Hi Bruce, I became aware of asciidoc __after__ I had put this framework together and
the madness of "flavors" of Markdown __during__.

While I find the Markdown landscape far from ideal, my perception is that at least
the basic Markdown features are better known among developers and therefore
"more approachable" than asciidoc. The limitations are currently covered by
various Pandoc Markdown extensions, which I find to be quite acceptable.

From the glimpse of asciidoc, I'm already convinced of its design and power but
I'm also convinced of the design and power of LaTeX. I might eventually decide that
even Pandoc Markdown isn't powerful enough and move to asciidoc... for now,
other users of the framework seem happy about being able to get off the ground
immediately with Markdown.
