### ISSUE TITLE
Implement wg21.link style look-up rule for references.

### ISSUE THREAD

**Issue by mpark** [mpark/wg21#27]
It would be useful to be able to cite something like `[@P0443]` and have it use the latest revision of that paper. As it is currently it expects the specific revision.

**Comment by m-ou-se** [comment]
Are you sure you want to reference something that changes meaning over time? Compiling a paper a year later could make it reference different papers than originally intended.

**Comment by mpark** [comment]
This is true... perhaps a better solution would be to show a better error message like: "References require a specific revision. The latest revision of Pxxxx is PxxxxRn"
