### ISSUE TITLE
p1260: possible customisation point

### ISSUE THREAD

**Issue by KantarBruceAdams** [mpark/wg21#3]
I wonder if "first match" semantics should actually be a customisation point?

Beyond the sequential implementaiton you might have an execution policy such as inspect(par) which could execute all matching choices in parallel. You could then implement [production systems](https://en.wikipedia.org/wiki/Production_system_(computer_science))  in the language directly. 
_par_ would be an object analogous to an executor rather than a simple enum.

**Comment by mpark** [comment]
I don't think there's a precedent for behavioral-changing customization point for a language feature in C++, and I also think such a customization point would make the feature too complex.
