### ISSUE TITLE
Python 3.9 posixpath not happy 

### ISSUE THREAD

**Issue by PeterSommerlad** [mpark/wg21#80]
Hi, I get several errors from wg21.py wrt to passing a NoneType to os.fspath()

any ideas how to fix?

I am a complete python newbie....

**Comment by PeterSommerlad** [comment]
I think the underlying issue is deeper because Pandoc seem to have changed too much between 2.9 and 2.11 and panflute also seems different enough with 2.0 that is required for 2.11....

**Comment by mpark** [comment]
This is most likely due to the API-incompatible changes in Pandoc 2.10. We now keep a pinned local installation of Pandoc to avoid this issue starting 1284389. We'll upgrade to a newer version when we're ready, but for now we'll avoid people being on different, API-incompatible versions of Pandoc.
