### ISSUE TITLE
caption type is blockquote that hinders some other filters

### ISSUE THREAD

**Issue by PeterSommerlad** [mpark/wg21#81]
The tonytables caption is generated from a blockquote in the span directly. While this is not a problem for pandoc itself, if combined with other filters (pandoc-tablenos) this can lead to problems, if such filters assume a node of type "Plain", such as pandoc-tablenos. It works, if an extra intermediate stage of markdown is used, but not directly.

The following code snippets show my changes for that:

```python
    def quote2plain(elem):
        result = pf.Plain()
        result.content = elem.content[0].content # switch from BlockQuote Para content to Plain
        return result 
    for elem in table.content:
        if isinstance(elem, pf.Header):
            if not isinstance(header, pf.Null):
                warn(header)

            if first_row:
                header = pf.Plain(*elem.content)
                if 'width' in elem.attributes:
                    width = float(elem.attributes['width'])
            else:
                warn(elem)
        elif isinstance(elem, pf.BlockQuote):
            caption = quote2plain(elem)
            kwargs['caption'].content.append(caption)
        #...
```
Feel free to close this issue immediately.

**Comment by mpark** [comment]
This is most likely due to the API-incompatible changes in Pandoc 2.10. We now keep a pinned local installation of Pandoc to avoid this issue starting 1284389. We'll upgrade to a newer version when we're ready, but for now we'll avoid people being on different, API-incompatible versions of Pandoc.
