### ISSUE TITLE
Improve readability on phones

### ISSUE THREAD

**Issue by RedBeard0531** [mpark/wg21#84]
I read most papers on my phone, but your default css has wide margins that make that difficult. Here's a screenshot  (using firefox dev tools responsive viewer) of a proposal I'm working on. I extended the length so that more would be visible, but the width is the same as on a Galaxy S9:

![before](https://user-images.githubusercontent.com/118456/114880223-2999ca80-9e02-11eb-99eb-9249797e9666.png)

Note how there are very few words per line, and how the metadata labels have fallen off the left edge.

I suggest two changes. Either set the margin to `1.5em` everywhere, or at least do it within a media query like this (it needs to go *after* the default `body` block): 

```css
@media screen and (max-width: 30em) {
    body {
	margin: 1.5em;
    }
}
```

Also, I suggest setting `text-align: justify;` on the `body`. It makes a big difference on mobile because the ragged edges are a larger percentage of the total width. But I also think it just looks better for prose even on a desktop.

Here is another screenshot with the modified CSS, or you'd like to quickly try it on any of your devices, [this draft paper](https://isocpp.org/files/papers/D2359R0.html) is using the patched CSS:

![after](https://user-images.githubusercontent.com/118456/114880729-99a85080-9e02-11eb-9f74-8fe0331a65e5.png)

If you would prefer, I'd be happy to make a PR with these changes.

**Comment by mpark** [comment]
Hey Mathias! Thanks for the feedback. Yes, the mobile experience seems it can be improved indeed. The specifics of your suggestions I'd have to learn more about, but I'd be happy to accept a patch if you're willing to submit one! The results do look better to me.
