### ISSUE TITLE
Spacing is inconsistent between references that have a URL and ones that don't

### ISSUE THREAD

**Issue by t3nsor** [mpark/wg21#95]
In PDF output, an extra blank line is inserted after a reference if and only if the reference has a URL:

![image](https://github.com/mpark/wg21/assets/949076/4c013488-4652-4d58-9915-704a05ac7011)

This inconsistent spacing is undesirable. I'm going to assume you like the version with the extra blank line better, so we need to make sure the blank line is always there regardless of whether we have a URL or not. But if you prefer it the other way (no blank line ever) then that's fine too. And if you don't have time to work on this, let me know and I'll send you a PR.

**Comment by mpark** [comment]
Fixed this today. Thanks for the report! Let me know if it's still broken :)
