### ISSUE TITLE
Problems with emphasis inside code blocks.

### ISSUE THREAD

**Issue by BengtGustafsson** [mpark/wg21#97]
I don't get my @-surrounded emphasis to work, instead it just writes the @**thing**@ to the pdf.

Same problem for html.

Same problem with both __ and ** use .

Here is a sample code block that doesn't work for me, the intent is to boldface the word typename, but instead it just outputs the @** and **@ sequences as is:

```C++
class MyClass {
    operator int() { return 0; }
    operator double() { return 1; }
};

auto conv = &MyClass::operator @**typename**@;

MyClass c;

int a = (c.*conv)();
double a = (c.*conv)();
```

**Comment by BengtGustafsson** [comment]
Well you have to check the source code obviously.

**Comment by BengtGustafsson** [comment]
I noted now that this only happens on one of my upcoming proposals, not the other. As this is rather strange, I attach the input and output file of the failing conversion for you to ponder over.
[ost.md](https://github.com/mpark/wg21/files/15283308/ost.md)
[ost.pdf](https://github.com/mpark/wg21/files/15283309/ost.pdf)

**Comment by mpark** [comment]
Hi @BengtGustafsson, this is due to the processing only being done on codeblocks with `cpp` as the language, rather than `C++`. Are you using `cpp` in the cases that work currently?

**Comment by BengtGustafsson** [comment]
Thanks for this explanation. It seems I use C++ a lot so that's why then. Unfortunately I didn't see your reply before the paper deadline so now I removed all those annotations...
